[mcp_servers.shadcn]
command = "npx"
args = [ "shadcn@latest", "mcp" ]

[mcp_servers.Neon]
type = "http"
url = "https://mcp.neon.tech/mcp?projectId=br-divine-rice-aofqklet"

[mcp_servers.Neon.http_headers]
Authorization = "Bearer napi_6aer97orxmypvz7hw0szlj62t841hhvreh3pmd9ajkr4vk1i5tx5hg35isljqi41"

