[mcp_servers.shadcn]
command = "npx"
args = [ "shadcn@latest", "mcp" ]

[mcp_servers.Neon]
type = "http"
url = "https://mcp.neon.tech/mcp?projectId=br-divine-rice-aofqklet"

[mcp_servers.Neon.http_headers]
Authorization = "Bearer napi_6aer97orxmypvz7hw0szlj62t841hhvreh3pmd9ajkr4vk1i5tx5hg35isljqi41"

[mcp_servers.stitch]
url = "https://stitch.googleapis.com/mcp"

[mcp_servers.stitch.http_headers]
"X-Goog-Api-Key" = "AQ.Ab8RN6JEfTo07zaAzyE7iOpWQ8eH5YaXGlr2Z4J34xNevaZP_g"
